#!/usr/bin/env python3
"""Coefficient ROM contents and preset-indexed vectors for modal_dp_rom.v, both
from model/modal_fixed.py (ModalFx.coefficients) so the ROM holds exactly the
model's words and tb_modal_rom.v can compare against the model with no tolerance.

Writes rtl-sketch/modal_coef_rom_p{4,8,16}.v and build/modal_rom_vectors_p{8,16}.hex
(P=4 gets a ROM only: verify_modal's stimulus uses a note it does not hold).
Run with the repo's .venv (numpy). See docs/area-budget.md section 3.
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
sys.path[:0] = [HERE, ROOT + '/model', ROOT + '/audition']
os.makedirs(os.path.join(HERE, 'build'), exist_ok=True)
import numpy as np, modal_fixed
from modal_fixed import ModalFx
import verify_modal
PRESETS = {4: [28, 40, 52, 88], 8: [28, 40, 52, 64, 76, 88, 100, 112],
           16: [28, 33, 38, 40, 45, 52, 57, 64, 69, 76, 83, 88, 94, 100, 106, 112]}
REV3 = dict(headroom=10, out_bits=16)   # the sizing modal_dp_rom.v / modal_dp_regs.v were built to
m0 = ModalFx(**REV3); CW = m0.CF + 2
for P, notes in PRESETS.items():
    PW = max(1, (P - 1).bit_length()); AW = PW + 4
    lines = [f'// GENERATED by gen_modal_rom.py: modal coefficient ROM, {P} presets = MIDI notes {notes},',
             f'// words from model/modal_fixed.py ModalFx().coefficients(note) with DEFAULT_MODES.',
             f'// addr = {{preset[{PW-1}:0], mode[1:0], kind[1:0]}}, kind 0 = a1, 1 = a2 (Q2.{m0.CF} signed), 2 = amp (Q0.16, zero-extended)',
             f'module modal_coef_rom #(parameter AW = {AW}, parameter DW = {CW}) (input wire [AW-1:0] addr, output reg [DW-1:0] data);',
             '    always @* begin', '        case (addr)']
    for p, note in enumerate(notes):
        for mode, (a1, a2, amp) in enumerate(ModalFx(**REV3).coefficients(note)):
            for kind, v in enumerate((a1, a2, amp)):
                lines.append(f"            {AW}'d{(p << 4) | (mode << 2) | kind}: data = {CW}'h{v & ((1 << CW) - 1):07X};")
    lines += [f"            default: data = {CW}'d0;", '        endcase', '    end', 'endmodule']
    open(os.path.join(HERE, f'modal_coef_rom_p{P}.v'), 'w').write('\n'.join(lines) + '\n')
    # vectors: exc, preset, expected y -- the exact stimulus of verify_modal.py, state carried across segments
    m = ModalFx(**REV3); out = []; ok = True
    for name, xq, note in verify_modal.bar_stimulus():
        if note not in notes: ok = False; break
        coefs = m.coefficients(note); y = m.process(xq, coefs); p = notes.index(note)
        for i in range(len(xq)):
            out.append(f"{int(xq[i]) & 0xffff:04x}{p:02x}{int(y[i]) & 0xffff:04x}\n")
    if ok:
        open(os.path.join(HERE, 'build', f'modal_rom_vectors_p{P}.hex'), 'w').writelines(out); print(f'P={P}: ROM + {len(out)} vectors')
    else:
        print(f'P={P}: ROM only (stimulus note {note} not among presets; synthesis-only)')
