// GENERATED by gen_modal_rom.py: modal coefficient ROM, 4 presets = MIDI notes [28, 40, 52, 88],
// words from model/modal_fixed.py ModalFx().coefficients(note) with DEFAULT_MODES.
// addr = {preset[1:0], mode[1:0], kind[1:0]}, kind 0 = a1, 1 = a2 (Q2.24 signed), 2 = amp (Q0.16, zero-extended)
module modal_coef_rom #(parameter AW = 6, parameter DW = 26) (input wire [AW-1:0] addr, output reg [DW-1:0] data);
    always @* begin
        case (addr)
            6'd0: data = 26'h1FFFB0F;
            6'd1: data = 26'h3000309;
            6'd2: data = 26'h000FFFF;
            6'd4: data = 26'h1FFED25;
            6'd5: data = 26'h3000456;
            6'd6: data = 26'h000999A;
            6'd8: data = 26'h1FFC259;
            6'd9: data = 26'h3000611;
            6'd10: data = 26'h0006666;
            6'd12: data = 26'h1FF5F57;
            6'd13: data = 26'h30008AB;
            6'd14: data = 26'h0004000;
            6'd16: data = 26'h1FFF557;
            6'd17: data = 26'h3000309;
            6'd18: data = 26'h000FFFF;
            6'd20: data = 26'h1FFC195;
            6'd21: data = 26'h3000456;
            6'd22: data = 26'h000999A;
            6'd24: data = 26'h1FF1BA3;
            6'd25: data = 26'h3000611;
            6'd26: data = 26'h0006666;
            6'd28: data = 26'h1FD97BA;
            6'd29: data = 26'h30008AB;
            6'd30: data = 26'h0004000;
            6'd32: data = 26'h1FFDE77;
            6'd33: data = 26'h3000309;
            6'd34: data = 26'h000FFFF;
            6'd36: data = 26'h1FF1362;
            6'd37: data = 26'h3000456;
            6'd38: data = 26'h000999A;
            6'd40: data = 26'h1FC8182;
            6'd41: data = 26'h3000611;
            6'd42: data = 26'h0006666;
            6'd44: data = 26'h1F67E8A;
            6'd45: data = 26'h30008AB;
            6'd46: data = 26'h0004000;
            6'd48: data = 26'h1F861A7;
            6'd49: data = 26'h3000309;
            6'd50: data = 26'h000FFFF;
            6'd52: data = 26'h1C6FC29;
            6'd53: data = 26'h3000456;
            6'd54: data = 26'h000999A;
            6'd56: data = 26'h1314163;
            6'd57: data = 26'h3000611;
            6'd58: data = 26'h0006666;
            6'd60: data = 26'h00F1FA5;
            6'd61: data = 26'h30008AB;
            6'd62: data = 26'h0004000;
            default: data = 26'd0;
        endcase
    end
endmodule
